apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:avi1234/hello-k8s.git
    targetRevision: HEAD
    path: argo_files
  destination:
    server: https://kubernetes.default.svc
    namespace: argoapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true